In [1]:
import numpy as np

In [2]:
a = np.arange(100,200,10)
a = a.reshape(5,2)
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [3]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray[0:,2])

[33 66 99]


In [4]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayThree = arrayOne + arrayTwo
print(arrayThree)

[[20 39 33]
 [25 25 28]]


In [5]:
print(np.square(arrayThree))

[[ 400 1521 1089]
 [ 625  625  784]]
